apiVersion: v1

kind: PersistentVolume

metadata:

name: pv-1

labels:

release: stable

capacity: 100Gi

spec:

capacity:

storage: 100Gi

volumeMode: Filesystem

accessModes:

- ReadWriteOnce

- ReadOnlyMany

persistentVolumeReclaimPolicy: Recycle

storageClassName: normal

nfs:

path: /tmp

server: 192.168.1.228
